environment:
  global:
    PROJECT_NAME: open2internet
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: 1.38.0

install:
#  - ps: Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-stable"
#  - ps: $env:RUST_VERSION = Get-Content channel-rust-stable | select -first 1 | %{$_.split('-')[1]}
  - SET RUST_URL=https://static.rust-lang.org/dist/rust-%RUST_VERSION%-%TARGET%.exe
  - SET PATH=C:\Rust\bin;C:\msys64\mingw64\bin;%PATH%;C:\msys64\usr\bin
  - SET PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig
  - ps: Start-FileDownload $env:RUST_URL -FileName rust-dist.exe
  - rust-dist.exe /VERYSILENT /NORESTART /COMPONENTS="Rustc,Gcc,Cargo,Std" /DIR="C:\Rust"
  - rustc -V
  - cargo -V
  - pacman --noconfirm -S mingw-w64-x86_64-gtk3
# for icon
  - pacman --noconfirm -S mingw-w64-x86_64-binutils
  - pacman --noconfirm -S mingw-w64-x86_64-gcc

build_script:
  - cargo test
  - cargo build --release

after_build:
  - cmd: after_build.bat
artifacts:
  - path: open2internet-mingw64.7z
    name: mingw64-bin

test: false