[package]
name = "open2internet"
version = "0.1.0"
authors = ["John Doe <john.doe@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
port_scanner = "0.1.5"
glib = "0.9.3"
gtk = "^0.8.0"
relm = "^0.19.0"
relm-derive = "^0.19.0"
igd = "0.10.0"
get_if_addrs = "0.5.3"