[package]
name = "open2internet"
version = "0.1.0"
authors = ["John Doe <john.doe@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
port_scanner = "0.1.5"